/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 pin.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pin(props) {
    const { nodes, materials } = useGLTF("/pin.gltf");
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Curve.geometry}
                material={materials.SVGMat}
                scale={1}
            />
        </group>
    );
}

useGLTF.preload("/pin.gltf");
